<?php

declare(strict_types=1);

namespace App\LaboratoryDictionary\Infrastructure\Doctrine\Migrations\Initial;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260529111920 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create reference_rule_active table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE laboratory_dictionary.reference_rule_active (
                            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            gender laboratory_dictionary.gender NOT NULL,
                            age_days_range INT4RANGE DEFAULT NULL,
                            pregnancy_trimester laboratory_dictionary.pregnancy_trimester,
                            menstrual_phase laboratory_dictionary.menstrual_phase,
                            normality_rule JSONB NOT NULL,
                            criticality_rule JSONB DEFAULT NULL,
                            interpretation_rule JSONB DEFAULT NULL,
                            priority INT NOT NULL,
                            test_definition_active_id TEXT NOT NULL,
                            PRIMARY KEY (id))');

        $this->addSql('CREATE INDEX idx_test_definition_active_id ON laboratory_dictionary.reference_rule_active (test_definition_active_id)');

        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rule_active
                                      ADD CONSTRAINT exclude_reference_ambiguity_active
                                      EXCLUDE USING gist (
                                                         test_definition_active_id WITH =,
                                                         gender WITH =,
                                                         age_days_range WITH &&,
                                                         pregnancy_trimester WITH =,
                                                         menstrual_phase WITH =
                                                         )');

        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rule_active ADD CONSTRAINT fk_test_definition_active_id FOREIGN KEY (test_definition_active_id) REFERENCES laboratory_dictionary.test_definitions_active (id) NOT DEFERRABLE');

        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rule_active ADD CONSTRAINT chk_priority CHECK (priority >= 0)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rule_active DROP CONSTRAINT fk_test_definition_active_id');
        $this->addSql('DROP TABLE laboratory_dictionary.reference_rule_active');
    }
}
