<?php

declare(strict_types=1);

namespace App\LaboratoryDictionary\Infrastructure\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518112711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {


        $this->addSql('CREATE TABLE laboratory_dictionary.reference_rules_active (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    gender laboratory_dictionary.gender NOT NULL,
                    age_days_range INT4RANGE DEFAULT NULL,
                    pregnancy_trimester laboratory_dictionary.pregnancy_trimester,
                    menstrual_phase laboratory_dictionary.menstrual_phase,
                    normality_rule JSONB NOT NULL,
                    criticality_rule JSONB DEFAULT NULL,
                    interpretation_rule JSONB DEFAULT NULL,
                    priority INT NOT NULL,
                    test_definition_active_id VARCHAR NOT NULL,
                    PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BCAE5BF3CF03040 ON laboratory_dictionary.reference_rules_active (test_definition_active_id)');

        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rules_active
                                      ADD CONSTRAINT exclude_reference_ambiguity_active
                                      EXCLUDE USING gist (
                                                         test_definition_active_id WITH =,
                                                         gender WITH =,
                                                         age_days_range WITH &&,
                                                         pregnancy_trimester WITH =,
                                                         menstrual_phase WITH =
                                                         )');


        $this->addSql('COMMENT ON TABLE laboratory_dictionary.reference_rules_active IS \'Contains EXCLUDE USING gist constraint for reference ambiguity\'');

        $this->addSql('CREATE TABLE laboratory_dictionary.reference_rules_draft (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    gender  laboratory_dictionary.gender NOT NULL,
                    age_days_range INT4RANGE DEFAULT NULL,
                    pregnancy_trimester laboratory_dictionary.pregnancy_trimester ,
                    menstrual_phase laboratory_dictionary.menstrual_phase,
                    normality_rule JSONB NOT NULL,
                    criticality_rule JSONB DEFAULT NULL,
                    interpretation_rule JSONB DEFAULT NULL,
                    priority INT NOT NULL,
                    test_definition_draft_id TEXT NOT NULL,
                    PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_948C3A00651BD06B ON laboratory_dictionary.reference_rules_draft (test_definition_draft_id)');
        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rules_draft
                          ADD CONSTRAINT exclude_reference_ambiguity_draft
                          EXCLUDE USING gist (
                                        test_definition_draft_id WITH =,
                                        gender WITH =,
                                        age_days_range WITH &&,
                                        pregnancy_trimester WITH =,
                                        menstrual_phase WITH =
    )');
        $this->addSql('COMMENT ON TABLE laboratory_dictionary.reference_rules_draft IS \'Contains EXCLUDE USING gist constraint for reference ambiguity\'');

        $this->addSql('CREATE TABLE laboratory_dictionary.test_definitions_active (
                      id TEXT NOT NULL,
                      official_name TEXT NOT NULL,
                      short_name TEXT NOT NULL,
                      loinc_code TEXT NOT NULL,
                      methodology TEXT NOT NULL,
                      unit_id UUID NOT NULL,
                      version INT NOT NULL,
                      specimen_definition_id UUID NOT NULL,
                      value_type laboratory_dictionary.value_type NOT NULL,
                      result_options JSONB DEFAULT NULL,
                      category_mnemonic TEXT NOT NULL,
                      PRIMARY KEY (id))');

        $this->addSql('CREATE UNIQUE INDEX UNIQ_C986303E49928441 ON laboratory_dictionary.test_definitions_active (official_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C986303E3EE4B093 ON laboratory_dictionary.test_definitions_active (short_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C986303EDDD484BF ON laboratory_dictionary.test_definitions_active (loinc_code)');
        $this->addSql('CREATE INDEX IDX_C986303E3A2C15A6 ON laboratory_dictionary.test_definitions_active (category_mnemonic)');

        $this->addSql('CREATE TABLE laboratory_dictionary.test_definitions_archive (
                     id TEXT NOT NULL,
                     official_name TEXT DEFAULT NULL,
                     short_name TEXT DEFAULT NULL,
                     loinc_code TEXT DEFAULT NULL,
                     methodology TEXT DEFAULT NULL,
                     reference_rules_snapshot JSONB DEFAULT NULL,
                     category_snapshot JSONB DEFAULT NULL,
                     unit_snapshot JSONB DEFAULT NULL,
                     version INT NOT NULL,
                     specimen_definition_snapshot JSONB DEFAULT NULL,
                     value_type laboratory_dictionary.value_type NOT NULL,
                     result_options JSONB DEFAULT NULL,
                     PRIMARY KEY (id, version))');

        $this->addSql('CREATE TABLE laboratory_dictionary.test_definitions_draft (
                     id TEXT NOT NULL,
                     official_name TEXT NOT NULL,
                     short_name TEXT NOT NULL,
                     loinc_code TEXT NOT NULL,
                     methodology TEXT NOT NULL,
                     category_mnemonic TEXT NOT NULL,
                     unit_id UUID NOT NULL,
                     version INT NOT NULL,
                     specimen_definition_id UUID NOT NULL,
                     value_type laboratory_dictionary.value_type NOT NULL,
                     result_options JSONB DEFAULT NULL,
                     PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D6446BC249928441 ON laboratory_dictionary.test_definitions_draft (official_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D6446BC23EE4B093 ON laboratory_dictionary.test_definitions_draft (short_name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D6446BC2DDD484BF ON laboratory_dictionary.test_definitions_draft (loinc_code)');

        $this->addSql('CREATE TABLE laboratory_dictionary.test_profiles (
                     code TEXT NOT NULL,
                     title TEXT NOT NULL,
                     PRIMARY KEY (code))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D4E62B52B36786B ON laboratory_dictionary.test_profiles (title)');

        $this->addSql('CREATE TABLE laboratory_dictionary.test_profile_test_definitions (
                     profile_code TEXT NOT NULL,
                     test_definition_id VARCHAR NOT NULL,
                     PRIMARY KEY (profile_code, test_definition_id))');
        $this->addSql('CREATE INDEX IDX_3D557B2FC1DDBF0C ON laboratory_dictionary.test_profile_test_definitions (profile_code)');
        $this->addSql('CREATE INDEX IDX_3D557B2FF7EB1F5D ON laboratory_dictionary.test_profile_test_definitions (test_definition_id)');
        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rules_active ADD CONSTRAINT FK_BCAE5BF3CF03040 FOREIGN KEY (test_definition_active_id) REFERENCES laboratory_dictionary.test_definitions_active (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rules_draft ADD CONSTRAINT FK_948C3A00651BD06B FOREIGN KEY (test_definition_draft_id) REFERENCES laboratory_dictionary.test_definitions_draft (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE laboratory_dictionary.test_definitions_active ADD CONSTRAINT FK_C986303E3A2C15A6 FOREIGN KEY (category_mnemonic) REFERENCES laboratory_dictionary.test_categories (mnemonic) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE laboratory_dictionary.test_profile_test_definitions ADD CONSTRAINT FK_3D557B2FC1DDBF0C FOREIGN KEY (profile_code) REFERENCES laboratory_dictionary.test_profiles (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE laboratory_dictionary.test_profile_test_definitions ADD CONSTRAINT FK_3D557B2FF7EB1F5D FOREIGN KEY (test_definition_id) REFERENCES laboratory_dictionary.test_definitions_active (id) NOT DEFERRABLE');

        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER filler DROP NOT NULL');
        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER temperature_condition DROP NOT NULL');
        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER stability_period DROP NOT NULL');
        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER preparation_requirements DROP NOT NULL');

    }

    public function down(Schema $schema): void
    {


        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rules_active DROP CONSTRAINT FK_BCAE5BF3CF03040');
        $this->addSql('ALTER TABLE laboratory_dictionary.reference_rules_draft DROP CONSTRAINT FK_948C3A00651BD06B');
        $this->addSql('ALTER TABLE laboratory_dictionary.test_definitions_active DROP CONSTRAINT FK_C986303E3A2C15A6');
        $this->addSql('ALTER TABLE laboratory_dictionary.test_profile_test_definitions DROP CONSTRAINT FK_3D557B2FC1DDBF0C');
        $this->addSql('ALTER TABLE laboratory_dictionary.test_profile_test_definitions DROP CONSTRAINT FK_3D557B2FF7EB1F5D');
        $this->addSql('DROP TABLE laboratory_dictionary.reference_rules_active');
        $this->addSql('DROP TABLE laboratory_dictionary.reference_rules_draft');
        $this->addSql('DROP TABLE laboratory_dictionary.test_definitions_active');
        $this->addSql('DROP TABLE laboratory_dictionary.test_definitions_archive');
        $this->addSql('DROP TABLE laboratory_dictionary.test_definitions_draft');
        $this->addSql('DROP TABLE laboratory_dictionary.test_profiles');
        $this->addSql('DROP TABLE laboratory_dictionary.test_profile_test_definitions');
        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER filler SET NOT NULL');
        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER temperature_condition SET NOT NULL');
        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER stability_period SET NOT NULL');
        $this->addSql('ALTER TABLE laboratory_dictionary.specimen_definitions ALTER preparation_requirements SET NOT NULL');

    }
}
